base_url = "https://prma.dev"
title = "prma"
description = "Permanent things do not need to be perfect."


default_language = "en"
build_search_index = true 
compile_sass = true
minify_html = true               # Whether to minify html code
theme = "no-style-please"
output_dir = "public"

generate_feed = true            # Whether to generate a feed file in root, read docs for more info about rss feed
# feed_filename = "feed.xml"       # The file name of feed, "feed.xml" / "atom.xml" / "rss.xml", read docs for more info

taxonomies = [
    {name = "tags"},             # Keep this
    {name = "categories"}        # Keep this
]

[markdown]
highlight_code = true
extra_syntaxes = []          
highlight_theme = "ascetic-white"         # The highlight theme, choose one at https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
# highlight_theme = "zenburn"         # The highlight theme, choose one at https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
render_emoji = false 

external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"

[extra]
name = "Amir Alesheikh"                    # Your name
id = "amirography"                      # Your id/username/handle
bio = "back-end developer / rustacean / gopher / previous cognitive science student / rationalist"                     # Your bio
logo = "img/avatar.png"       # Your avatar

# show_id = true                   # Whether to show your id in homepage
# show_projects = false             # Whether to show projects page

#============== Icons, you can choose at https://remixicon.com/ ====
# blog_icon = "ri-pen-nib-line"          
# projects_icon = "ri-compasses-2-line"
# home_icon = "ri-user-6-line"
# rss_icon = "ri-rss-line"
# toc_icon = "ri-menu-2-line"

#============== Social media links =================================
# links = [
#     {name = "Mastodon", icon = "ri-mastodon-line", url = "https://fosstodon.org/@Amirography"},
#     {name = "GitHub", icon = "ri-github-line", url = "https://github.com/amirography"},
#     {name = "Linkedin", icon = "ri-linkedin-line", url = "https://linkedin.com/in/amirography"},
#     {name = "Twitter", icon = "ri-twitter-line", url = "https://twitter.com/amirography"},
#     # Your can add more links
# ]

#============== Feed ===============================================
# feed_in_blog_section = true      # Whether to make feed file in blog section, url will be https://example.com/blog/feed.xml, read docs for more info about rss feed

#============== Some feature switches ================================
# toc = true                       # Whether to show Table-Of-Contents [Can be overridden by page config]
# blur_effect = false               # Whether to turn on blur effect on navigation bar
# back_to_top_button = true        # Whether to show Back-To-Top button
# progress_bar = true              # Whether to show reading progress bar
# cc_license = false               # Whether to show Creative-Commons statement [Can be overridden by page config]
# cc_license_statement = "This work is licensed under [CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/)."  # The Creative-Commons statement
# outdate_warn = false             # Whether to show outdate warning [Can be overridden by page config]

#============== Footer =============================================
# footer_copyright_name = "amirography"
# footer_copyright_year = "2022"
# footer_credits = false            # Whether to show "Powered by Zola and Serene" in footer

# comment = "none"                 # gitalk / disqus / disqus_js
# analytics = "none"               # google_analytics / cloudflare_web_analytics / umami / baidu_tongji
#============================ 

header_nav = [
    { name = "~ home", url = "/" },
    { name = "# tags", url = "/tags" },
    { name = "+ categories", url = "/categories" },
    { name = "> about_me", url = "/about_me" },
    { name = "> about_prma", url = "/about_prma" },
    # { name = "@contexts", url = "/contexts" },
    # { name = "example", url = "http://example.com", new_tab=true },
]
list_pages = true

footer_nav = [
    # { name = "< previous", url = "#" },
    # { name = "webring", url = "#" },
    # { name = "next >", url = "#" },
]

twitter_card = false